services:
  - type: web
    name: interviewiq-api
    runtime: node
    region: oregon
    plan: free
    rootDir: InterviewIQ/backend 
    buildCommand: npm install && pip3 install -r ../ai-service/requirements.txt --break-system-packages
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
